services:
  php:
    container_name: php8
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./backend:/var/www/html
    networks:
      - meta_network
    depends_on:
      - mysql
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=meta
      - MYSQL_PASS=secret
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - meta_network
  moodle:
    image: docker.io/bitnami/moodle:4.5
    ports:
      - 8070:8080
      - 443:8443
    environment:
      - MOODLE_DATABASE_HOST=mysql
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_NAME=root
      - MOODLE_DATABASE_PASSWORD=secret
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      - mysql
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - meta_network
    volumes:
      - ./backend/:/var/www/html/
      - ./logs/nginx:/var/log/nginx
    container_name: nginx

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - meta_network
networks:
  meta_network:

volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local